micronaut:
  application:
    name: gateway
  server:
    port: 8080
  executors:
    io:
      type: fixed
      n-threads: 5

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db
    driverClassName: org.postgresql.Driver
    username: user
    password: "password"
    dialect: postgres
    maximum-pool-size: 1
    connection-test-query: "select 1"

flyway:
  datasources:
    default:
      enabled: true

jackson:
  serialization-inclusion: always
  property-naming-strategy: SNAKE_CASE

fm:
  iam:
    server:
      host: localhost
      port: 50052

minio:
  server:
    host: localhost
    port: 9000
  username: minio
  password: minio123
